export const CLICK_DATE = "CLICK_DATE";
export const CLICK_PREV_BUTTON = "CLICK_PREV_BUTTON";
export const CLICK_NEXT_BUTTON = "CLICK_NEXT_BUTOON";
export const CLICK_THISMONTH_BUTTON = "CLICK_THISMONTH_BUTTON";